baseURL: https://kolja.krückmeyer.de/
languageCode: en-GB
title: Kolja Marius Krückmeyer
theme: "toha"
author:
  name: Kolja Marius Krückmeyer

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
defaultContentLanguage: de
languages:
  de:
    languageName: Deutsch
    weight: 1
  en:
    languageName: English
    weight: 2

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # GitHub repo URL and branch of your site
  gitRepo: https://github.com/KoljaKrueckmeyer/KoljaKrueckmeyer.github.io
  gitBranch: main

  # specify whether you want to write some blog posts or not
  enableBlogPost: false

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  background: /images/background/space-19070.jpg
  # Configure various features of this theme
  features:
    # Enable and configure portfolio
    portfolio:
      enable: true
    # Enable and configure blog posts
    blog:
      enable: false
      # Share post on different social media
      shareButtons:
        facebook: true
        twitter: false
        linkedin: true
        reddit: false
        whatsapp: false
        email: true
        # tumblr: true
        # pocket: true
        # diaspora: true
        # mastodon: true
    notes:
      enable: false

  # Provide newsletter configuration.
  # This feature has been implemented for Mailchimp only for now.
  # You can also hide it from the footer.
  newsletter:
    # specify whether you want to display the newsletter form
    enable: false
    # specify which newsletter provider you want to use
    provider: mailchimp
    # specify the target URL for the subscription form
    mailchimpURL: https://github.us1.list-manage.com/subscribe/post?u=19de52a4603135aae97163fd8&amp;id=094a24c76e

  # Provide footer configuration.
  footer:
    enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: true
    # Show/hide "Contact Me" section in the footer. Default is "true".
    contactMe:
      enable: true
    # Show/hide credentials section in the footer. Default is "true".
    credentials:
      enable: true